{
 "title": "BankPulse Platform Overview",
 "tags": [
  "bankpulse",
  "lab",
  "observability"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Payments API UP",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "up{job=\"payments-api\"}"
    }
   ]
  },
  {
   "title": "Audit API UP",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 0 },
   "targets": [
    {
     "expr": "up{job=\"audit-api\"}"
    }
   ]
  },
  {
   "title": "HTTP requests / second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum by (job) (rate(http_server_requests_seconds_count[1m]))",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "JVM heap used",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (job) (jvm_memory_used_bytes{area=\"heap\"})",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Container CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum by (name) (rate(container_cpu_usage_seconds_total{name!=\"\"}[1m]))",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}